# Generated by Django 6.0.2 on 2026-02-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("video_file", models.FileField(upload_to="videos/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("uploader_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "uploader_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uploader_device",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
