# Generated by Django 6.0.2 on 2026-02-26 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_videopost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=100)),
                ("promotion_title", models.CharField(max_length=200)),
                (
                    "target_url",
                    models.URLField(help_text="Where should users go when they click?"),
                ),
                ("ad_image", models.ImageField(upload_to="promotions/")),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basic", "Sidebar - 7 Days ($10)"),
                            ("premium", "Featured Header - 3 Days ($25)"),
                            ("gold", "Full Page Takeover - 1 Day ($50)"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
